"""Added new fields to Users

Revision ID: 0981f8692ed1
Revises: 
Create Date: 2024-01-10 15:11:03.818133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0981f8692ed1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spend_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('spend_month', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('leads_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('leads_count')
        batch_op.drop_column('spend_month')
        batch_op.drop_column('spend_total')

    # ### end Alembic commands ###
