"""changed image urls to ids

Revision ID: 9009c62c7e14
Revises: 0981f8692ed1
Create Date: 2024-01-11 10:25:10.198241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9009c62c7e14'
down_revision = '0981f8692ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_image_url')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('media_id')

    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('profile_image_id')

    # ### end Alembic commands ###
